runtime: python311
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50
entrypoint: gunicorn -b :$PORT main:app
